version: '3.8'
services:
  backend:
    build: .
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./afsp_app:/app/afsp_app
      - ./afsp_app/uploads:/app/afsp_app/uploads
      - ./afsp_app/downloads:/app/afsp_app/downloads
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./afsp_app/afsp.db:/app/afsp_app/afsp.db
    environment:
      - PYTHONUNBUFFERED=1
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
